/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkItemsRouteImport } from './routes/work-items'
import { Route as ProjectsManageRouteImport } from './routes/projects-manage'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as DocumentRouteImport } from './routes/document'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkItemsBacklogRouteImport } from './routes/work-items/backlog'
import { Route as WorkItemsIdRouteImport } from './routes/work-items/$id'
import { Route as DocumentIdRouteImport } from './routes/document/$id'
import { Route as WorkItemsNewEditRouteImport } from './routes/work-items/new.edit'
import { Route as WorkItemsIdEditRouteImport } from './routes/work-items/$id.edit'
import { Route as ProjectsNewEditRouteImport } from './routes/projects/new.edit'
import { Route as ProjectsIdEditRouteImport } from './routes/projects/$id.edit'
import { Route as DocumentNewEditRouteImport } from './routes/document/new.edit'
import { Route as DocumentIdEditRouteImport } from './routes/document/$id.edit'

const WorkItemsRoute = WorkItemsRouteImport.update({
  id: '/work-items',
  path: '/work-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsManageRoute = ProjectsManageRouteImport.update({
  id: '/projects-manage',
  path: '/projects-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentRoute = DocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkItemsBacklogRoute = WorkItemsBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => WorkItemsRoute,
} as any)
const WorkItemsIdRoute = WorkItemsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkItemsRoute,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentRoute,
} as any)
const WorkItemsNewEditRoute = WorkItemsNewEditRouteImport.update({
  id: '/new/edit',
  path: '/new/edit',
  getParentRoute: () => WorkItemsRoute,
} as any)
const WorkItemsIdEditRoute = WorkItemsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorkItemsIdRoute,
} as any)
const ProjectsNewEditRoute = ProjectsNewEditRouteImport.update({
  id: '/projects/new/edit',
  path: '/projects/new/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/projects/$id/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentNewEditRoute = DocumentNewEditRouteImport.update({
  id: '/new/edit',
  path: '/new/edit',
  getParentRoute: () => DocumentRoute,
} as any)
const DocumentIdEditRoute = DocumentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DocumentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/document': typeof DocumentRouteWithChildren
  '/overview': typeof OverviewRoute
  '/projects-manage': typeof ProjectsManageRoute
  '/work-items': typeof WorkItemsRouteWithChildren
  '/document/$id': typeof DocumentIdRouteWithChildren
  '/work-items/$id': typeof WorkItemsIdRouteWithChildren
  '/work-items/backlog': typeof WorkItemsBacklogRoute
  '/document/$id/edit': typeof DocumentIdEditRoute
  '/document/new/edit': typeof DocumentNewEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/new/edit': typeof ProjectsNewEditRoute
  '/work-items/$id/edit': typeof WorkItemsIdEditRoute
  '/work-items/new/edit': typeof WorkItemsNewEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/document': typeof DocumentRouteWithChildren
  '/overview': typeof OverviewRoute
  '/projects-manage': typeof ProjectsManageRoute
  '/work-items': typeof WorkItemsRouteWithChildren
  '/document/$id': typeof DocumentIdRouteWithChildren
  '/work-items/$id': typeof WorkItemsIdRouteWithChildren
  '/work-items/backlog': typeof WorkItemsBacklogRoute
  '/document/$id/edit': typeof DocumentIdEditRoute
  '/document/new/edit': typeof DocumentNewEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/new/edit': typeof ProjectsNewEditRoute
  '/work-items/$id/edit': typeof WorkItemsIdEditRoute
  '/work-items/new/edit': typeof WorkItemsNewEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/backlog': typeof BacklogRoute
  '/document': typeof DocumentRouteWithChildren
  '/overview': typeof OverviewRoute
  '/projects-manage': typeof ProjectsManageRoute
  '/work-items': typeof WorkItemsRouteWithChildren
  '/document/$id': typeof DocumentIdRouteWithChildren
  '/work-items/$id': typeof WorkItemsIdRouteWithChildren
  '/work-items/backlog': typeof WorkItemsBacklogRoute
  '/document/$id/edit': typeof DocumentIdEditRoute
  '/document/new/edit': typeof DocumentNewEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/new/edit': typeof ProjectsNewEditRoute
  '/work-items/$id/edit': typeof WorkItemsIdEditRoute
  '/work-items/new/edit': typeof WorkItemsNewEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/backlog'
    | '/document'
    | '/overview'
    | '/projects-manage'
    | '/work-items'
    | '/document/$id'
    | '/work-items/$id'
    | '/work-items/backlog'
    | '/document/$id/edit'
    | '/document/new/edit'
    | '/projects/$id/edit'
    | '/projects/new/edit'
    | '/work-items/$id/edit'
    | '/work-items/new/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/backlog'
    | '/document'
    | '/overview'
    | '/projects-manage'
    | '/work-items'
    | '/document/$id'
    | '/work-items/$id'
    | '/work-items/backlog'
    | '/document/$id/edit'
    | '/document/new/edit'
    | '/projects/$id/edit'
    | '/projects/new/edit'
    | '/work-items/$id/edit'
    | '/work-items/new/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/backlog'
    | '/document'
    | '/overview'
    | '/projects-manage'
    | '/work-items'
    | '/document/$id'
    | '/work-items/$id'
    | '/work-items/backlog'
    | '/document/$id/edit'
    | '/document/new/edit'
    | '/projects/$id/edit'
    | '/projects/new/edit'
    | '/work-items/$id/edit'
    | '/work-items/new/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BacklogRoute: typeof BacklogRoute
  DocumentRoute: typeof DocumentRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  ProjectsManageRoute: typeof ProjectsManageRoute
  WorkItemsRoute: typeof WorkItemsRouteWithChildren
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
  ProjectsNewEditRoute: typeof ProjectsNewEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-items': {
      id: '/work-items'
      path: '/work-items'
      fullPath: '/work-items'
      preLoaderRoute: typeof WorkItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects-manage': {
      id: '/projects-manage'
      path: '/projects-manage'
      fullPath: '/projects-manage'
      preLoaderRoute: typeof ProjectsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document': {
      id: '/document'
      path: '/document'
      fullPath: '/document'
      preLoaderRoute: typeof DocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-items/backlog': {
      id: '/work-items/backlog'
      path: '/backlog'
      fullPath: '/work-items/backlog'
      preLoaderRoute: typeof WorkItemsBacklogRouteImport
      parentRoute: typeof WorkItemsRoute
    }
    '/work-items/$id': {
      id: '/work-items/$id'
      path: '/$id'
      fullPath: '/work-items/$id'
      preLoaderRoute: typeof WorkItemsIdRouteImport
      parentRoute: typeof WorkItemsRoute
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/work-items/new/edit': {
      id: '/work-items/new/edit'
      path: '/new/edit'
      fullPath: '/work-items/new/edit'
      preLoaderRoute: typeof WorkItemsNewEditRouteImport
      parentRoute: typeof WorkItemsRoute
    }
    '/work-items/$id/edit': {
      id: '/work-items/$id/edit'
      path: '/edit'
      fullPath: '/work-items/$id/edit'
      preLoaderRoute: typeof WorkItemsIdEditRouteImport
      parentRoute: typeof WorkItemsIdRoute
    }
    '/projects/new/edit': {
      id: '/projects/new/edit'
      path: '/projects/new/edit'
      fullPath: '/projects/new/edit'
      preLoaderRoute: typeof ProjectsNewEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/projects/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/new/edit': {
      id: '/document/new/edit'
      path: '/new/edit'
      fullPath: '/document/new/edit'
      preLoaderRoute: typeof DocumentNewEditRouteImport
      parentRoute: typeof DocumentRoute
    }
    '/document/$id/edit': {
      id: '/document/$id/edit'
      path: '/edit'
      fullPath: '/document/$id/edit'
      preLoaderRoute: typeof DocumentIdEditRouteImport
      parentRoute: typeof DocumentIdRoute
    }
  }
}

interface DocumentIdRouteChildren {
  DocumentIdEditRoute: typeof DocumentIdEditRoute
}

const DocumentIdRouteChildren: DocumentIdRouteChildren = {
  DocumentIdEditRoute: DocumentIdEditRoute,
}

const DocumentIdRouteWithChildren = DocumentIdRoute._addFileChildren(
  DocumentIdRouteChildren,
)

interface DocumentRouteChildren {
  DocumentIdRoute: typeof DocumentIdRouteWithChildren
  DocumentNewEditRoute: typeof DocumentNewEditRoute
}

const DocumentRouteChildren: DocumentRouteChildren = {
  DocumentIdRoute: DocumentIdRouteWithChildren,
  DocumentNewEditRoute: DocumentNewEditRoute,
}

const DocumentRouteWithChildren = DocumentRoute._addFileChildren(
  DocumentRouteChildren,
)

interface WorkItemsIdRouteChildren {
  WorkItemsIdEditRoute: typeof WorkItemsIdEditRoute
}

const WorkItemsIdRouteChildren: WorkItemsIdRouteChildren = {
  WorkItemsIdEditRoute: WorkItemsIdEditRoute,
}

const WorkItemsIdRouteWithChildren = WorkItemsIdRoute._addFileChildren(
  WorkItemsIdRouteChildren,
)

interface WorkItemsRouteChildren {
  WorkItemsIdRoute: typeof WorkItemsIdRouteWithChildren
  WorkItemsBacklogRoute: typeof WorkItemsBacklogRoute
  WorkItemsNewEditRoute: typeof WorkItemsNewEditRoute
}

const WorkItemsRouteChildren: WorkItemsRouteChildren = {
  WorkItemsIdRoute: WorkItemsIdRouteWithChildren,
  WorkItemsBacklogRoute: WorkItemsBacklogRoute,
  WorkItemsNewEditRoute: WorkItemsNewEditRoute,
}

const WorkItemsRouteWithChildren = WorkItemsRoute._addFileChildren(
  WorkItemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BacklogRoute: BacklogRoute,
  DocumentRoute: DocumentRouteWithChildren,
  OverviewRoute: OverviewRoute,
  ProjectsManageRoute: ProjectsManageRoute,
  WorkItemsRoute: WorkItemsRouteWithChildren,
  ProjectsIdEditRoute: ProjectsIdEditRoute,
  ProjectsNewEditRoute: ProjectsNewEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
